### ISSUE TITLE
format for correct pretty level

### ISSUE THREAD

**Issue by Shmurdik** [rossengeorgiev/vdf-parser#11]
foreach($arr as $k => $v) {
        if(is_string($v)) {
            $buf .= sprintf("%s\"%s\" \"%s\"\n", $line_indent, $k, $v);
        }
        else {
            $res = vdf_encode_step($v, $pretty, $level + 1);
            if($res === NULL) return NULL;

            $buf .= sprintf("%1\$s\"%2\$s\"\n%1\$s{\n%3\$s%1\$s}\n", $line_indent, $k, $res);
        }
    }

**Comment by rossengeorgiev** [comment]
Thank. Will you submit a PR ?

**Comment by Shmurdik** [comment]
done
