### ISSUE TITLE
The online version doesn't seem to work on steam controller .vdf files

### ISSUE THREAD

**Issue by JeffreySpring** [rossengeorgiev/vdf-parser#18]

**Comment by JeffreySpring** [comment]
The online version doesn't seem to work on steam controller .vdf files. 
It seems to strip away most of the controller's bindings 
[controller_configurationD.vdf.txt](https://github.com/rossengeorgiev/vdf-parser/files/1202921/controller_configurationD.vdf.txt)

**Comment by rossengeorgiev** [comment]
That is correct. If you look at the VDF it has multiple keys with the same name. That not possible in JSON.

https://github.com/ValvePython/vdf is a python module that provides a way to deal with duplicate keys.

**Comment by rossengeorgiev** [comment]
Closing as stale
