### ISSUE TITLE
Non quoted names are not parsed

### ISSUE THREAD

**Issue by andygrunwald** [rossengeorgiev/vdf-parser#4]
According to https://developer.valvesoftware.com/wiki/KeyValues: `It has 3 control characters {, } and ". Names and values may be quoted or not.`.

This means:
```
"ParentKey1"
{
	ValueKey1	"1"
}
```

should result in 

```
array(1) {
  'ParentKey1' =>
  array(1) {
    'ValueKey1' =>
    string(1) "1"
  }
}
```

but results in 

```
array(1) {
  'ParentKey1' =>
  array(0) {
  }
}
```

**Comment by rossengeorgiev** [comment]
Had forgotten to fix. Thanks!
