### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by howardchung** [rossengeorgiev/vdf-parser#8]
It would be nice to have this published to npm.  There's https://www.npmjs.com/package/vdfjs but it doesn't seem to work properly on the item schema.

**Comment by rossengeorgiev** [comment]
I look into to it. Have you tried this for parsing the items schema?

**Comment by howardchung** [comment]
Yes, it seemed to work fine :)

**Comment by rossengeorgiev** [comment]
Cool. Now the hardest part, to think of name to use for npm as the easy ones are already taken.

**Comment by howardchung** [comment]
https://www.npmjs.com/package/vdf-parser

They even give you directions lol

**Comment by rossengeorgiev** [comment]
I always liked directions

```bash
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! message SSL Error: CERT_UNTRUSTED

**Comment by rossengeorgiev** [comment]
There we go. https://www.npmjs.com/package/simple-vdf
